# Cross-package numerical tests against the Julia reference oracle.
#
# The oracle (tests/testthat/data/cross_oracle.json) is generated by running
# scripts/build_cross_oracle.jl inside the sibling DistributionsFactories.jl
# repo (https://github.com/Distribution-Matching/DistributionsFactories.jl).
# A single invocation writes the oracle into both this R package's
# tests/testthat/data/ directory and the Python sibling package's
# tests/data/ directory.
#
# For each (py_name, kwargs) case in the oracle, this test runs make_dist()
# in R and checks that the resulting distribution's mean, variance, and
# selected quantiles match the Julia reference within a generous tolerance.
# Cases for families this R package does not yet implement are filtered out
# at load time.
#
# If jsonlite is not installed, or the oracle file is missing, these tests
# skip rather than fail.

oracle_path <- function() {
  # testthat::test_path resolves to tests/testthat/ both interactively and
  # under R CMD check.
  testthat::test_path("data", "cross_oracle.json")
}

# Families this R package currently implements. The oracle JSON is the full
# Julia battery; we filter at load time to whatever R covers today. As more
# families are added to the R package, extend this vector — eventually it
# should reach Julia/Python parity.
SUPPORTED_FAMILIES <- c("gamma", "exponential", "logistic", "beta", "normal",
                        "lognormal", "uniform", "weibull", "tdist", "chisq",
                        "fdist", "laplace", "gumbel", "rayleigh", "pareto",
                        "frechet", "inverse_gamma", "chi", "folded_normal",
                        "erlang", "sym_triangular", "triangular",
                        "binomial", "poisson", "negative_binomial", "geometric",
                        "discrete_uniform", "discrete_sym_triangular",
                        "discrete_triangular")

closed_form_mean <- function(name, params) {
  switch(
    name,
    gamma       = params$shape / params$rate,
    exponential = 1 / params$rate,
    logistic    = params$location,
    beta        = params$shape1 / (params$shape1 + params$shape2),
    normal      = params$mean,
    lognormal   = exp(params$meanlog + params$sdlog^2 / 2),
    uniform     = (params$min + params$max) / 2,
    weibull     = params$scale * gamma(1 + 1 / params$shape),
    tdist       = 0,
    chisq       = params$df,
    fdist       = params$df2 / (params$df2 - 2),
    laplace     = params$location,
    gumbel      = params$location + params$scale * (-digamma(1)),
    rayleigh    = params$scale * sqrt(pi / 2),
    pareto      = params$shape * params$scale / (params$shape - 1),
    frechet     = params$scale * gamma(1 - 1 / params$shape),
    inverse_gamma = params$scale / (params$shape - 1),
    chi           = sqrt(2) * exp(lgamma((params$df + 1) / 2) - lgamma(params$df / 2)),
    folded_normal = {
      mu <- params$location; sigma <- params$scale
      sigma * sqrt(2 / pi) * exp(-mu^2 / (2 * sigma^2)) +
        mu * (1 - 2 * pnorm(-mu / sigma))
    },
    erlang        = params$shape * params$scale,
    sym_triangular = params$location,
    triangular    = (params$a + params$b + params$c) / 3,
    binomial      = params$size * params$prob,
    poisson       = params$lambda,
    negative_binomial = params$size * (1 - params$prob) / params$prob,
    geometric     = (1 - params$prob) / params$prob,
    discrete_uniform = (params$min + params$max) / 2,
    discrete_sym_triangular = params$mu,
    discrete_triangular = {
      a <- params$a; b <- params$b; c <- params$c
      Z <- (b - a + 2) / 2
      ks <- a:b
      pmf <- ifelse(ks <= c, (ks - a + 1) / (c - a + 1) / Z,
                              (b - ks + 1) / (b - c + 1) / Z)
      sum(ks * pmf)
    },
    stop("no closed-form mean wired for ", name)
  )
}

closed_form_var <- function(name, params) {
  switch(
    name,
    gamma       = params$shape / params$rate^2,
    exponential = 1 / params$rate^2,
    logistic    = (pi^2 / 3) * params$scale^2,
    beta        = {
      a <- params$shape1; b <- params$shape2
      a * b / ((a + b)^2 * (a + b + 1))
    },
    normal      = params$sd^2,
    lognormal   = {
      s2 <- params$sdlog^2
      (exp(s2) - 1) * exp(2 * params$meanlog + s2)
    },
    uniform     = (params$max - params$min)^2 / 12,
    weibull     = {
      g1 <- gamma(1 + 1 / params$shape); g2 <- gamma(1 + 2 / params$shape)
      params$scale^2 * (g2 - g1^2)
    },
    tdist       = params$df / (params$df - 2),
    chisq       = 2 * params$df,
    fdist       = {
      d1 <- params$df1; d2 <- params$df2
      2 * d2^2 * (d1 + d2 - 2) / (d1 * (d2 - 2)^2 * (d2 - 4))
    },
    laplace     = 2 * params$scale^2,
    gumbel      = (pi^2 / 6) * params$scale^2,
    rayleigh    = params$scale^2 * (4 - pi) / 2,
    pareto      = {
      a <- params$shape; xm <- params$scale
      (xm^2 * a) / ((a - 1)^2 * (a - 2))
    },
    frechet     = {
      a <- params$shape; sg <- params$scale
      g1 <- gamma(1 - 1 / a); g2 <- gamma(1 - 2 / a)
      sg^2 * (g2 - g1^2)
    },
    inverse_gamma = {
      a <- params$shape; b <- params$scale
      b^2 / ((a - 1)^2 * (a - 2))
    },
    chi           = {
      m <- sqrt(2) * exp(lgamma((params$df + 1) / 2) - lgamma(params$df / 2))
      params$df - m^2
    },
    folded_normal = {
      mu <- params$location; sigma <- params$scale
      m <- sigma * sqrt(2 / pi) * exp(-mu^2 / (2 * sigma^2)) +
           mu * (1 - 2 * pnorm(-mu / sigma))
      mu^2 + sigma^2 - m^2
    },
    erlang        = params$shape * params$scale^2,
    sym_triangular = params$scale^2 / 6,
    triangular    = {
      a <- params$a; b <- params$b; c <- params$c
      (a^2 + b^2 + c^2 - a * b - a * c - b * c) / 18
    },
    binomial      = params$size * params$prob * (1 - params$prob),
    poisson       = params$lambda,
    negative_binomial = params$size * (1 - params$prob) / params$prob^2,
    geometric     = (1 - params$prob) / params$prob^2,
    discrete_uniform = ((params$max - params$min + 1)^2 - 1) / 12,
    discrete_sym_triangular = params$n * (params$n + 2) / 6,
    discrete_triangular = {
      a <- params$a; b <- params$b; c <- params$c
      Z <- (b - a + 2) / 2
      ks <- a:b
      pmf <- ifelse(ks <= c, (ks - a + 1) / (c - a + 1) / Z,
                              (b - ks + 1) / (b - c + 1) / Z)
      m <- sum(ks * pmf)
      sum((ks - m)^2 * pmf)
    },
    stop("no closed-form var wired for ", name)
  )
}

coerce_kwargs <- function(kw) {
  # The oracle emits "quantiles" as a list of two-element lists; convert
  # those back to a list of length-2 numeric vectors (the R API form).
  out <- kw
  if (!is.null(kw$quantiles)) {
    out$quantiles <- lapply(kw$quantiles, function(pair) as.numeric(unlist(pair)))
  }
  out
}

parse_value <- function(x) {
  if (is.character(x)) {
    if (x == "inf") return(Inf)
    if (x == "-inf") return(-Inf)
    if (x == "nan") return(NaN)
  }
  as.numeric(x)
}

skip_if_no_oracle <- function() {
  testthat::skip_if_not_installed("jsonlite")
  path <- oracle_path()
  if (!file.exists(path)) {
    testthat::skip(sprintf("Oracle missing: %s", path))
  }
  path
}

load_oracle <- function() {
  path <- skip_if_no_oracle()
  jsonlite::fromJSON(path, simplifyVector = FALSE)
}


test_that("cross-oracle constructors agree with Julia", {
  oracle <- load_oracle()
  cases <- Filter(function(c) c$py_name %in% SUPPORTED_FAMILIES, oracle$constructors)
  testthat::expect_gt(length(cases), 0)

  for (case in cases) {
    name <- case$py_name
    kw <- coerce_kwargs(case$kwargs)
    expected <- case$expected
    label <- sprintf("%s(%s)", name,
                     paste(names(kw), "=", sapply(kw, function(v) {
                       if (is.list(v)) "quantiles" else format(v)
                     }), collapse = ", "))

    d <- do.call(make_dist, c(list(dist = name), kw))

    exp_mean <- parse_value(expected$mean)
    exp_var  <- parse_value(expected$var)

    if (is.finite(exp_mean)) {
      got <- closed_form_mean(name, d$params)
      testthat::expect_equal(got, exp_mean, tolerance = 1e-5,
                             info = sprintf("%s: mean", label))
    }
    if (is.finite(exp_var)) {
      got <- closed_form_var(name, d$params)
      testthat::expect_equal(got, exp_var, tolerance = 1e-5,
                             info = sprintf("%s: var", label))
    }

    # Quantile parity via $q (continuous only — discrete families would
    # disagree on tie-breaking conventions, but R only covers continuous
    # families anyway).
    if (isFALSE(expected$discrete) && !is.null(expected$ppf)) {
      for (p_str in names(expected$ppf)) {
        p <- as.numeric(p_str)
        q_jl <- parse_value(expected$ppf[[p_str]])
        if (!is.finite(q_jl)) next
        q_r <- d$q(p)
        testthat::expect_equal(q_r, q_jl, tolerance = 1e-5,
                               info = sprintf("%s: q(%s)", label, p_str))
      }
    }
  }
})


test_that("cross-oracle dist_exists agrees with Julia", {
  oracle <- load_oracle()
  # R does not yet support the `support=` (truncation) kwarg, so skip any
  # feasibility cases that depend on it.
  cases <- Filter(
    function(c) c$py_name %in% SUPPORTED_FAMILIES && is.null(c$support),
    oracle$feasibility
  )
  testthat::expect_gt(length(cases), 0)

  for (case in cases) {
    name <- case$py_name
    kw <- coerce_kwargs(case$kwargs)
    expected <- isTRUE(case$expected)
    label <- sprintf("%s(%s)", name,
                     paste(names(kw), "=", sapply(kw, format),
                           collapse = ", "))

    actual <- do.call(dist_exists, c(list(dist = name), kw))
    testthat::expect_identical(actual, expected, info = label)
  }
})
