# Cross-package numerical tests against the Julia reference oracle.
#
# The oracle (tests/testthat/data/cross_oracle.json) is generated by running
# scripts/build_cross_oracle.jl inside the sibling DistributionsFactories.jl
# repo (https://github.com/Distribution-Matching/DistributionsFactories.jl).
# A single invocation writes the oracle into both this R package's
# tests/testthat/data/ directory and the Python sibling package's
# tests/data/ directory.
#
# For each (py_name, kwargs) case in the oracle, this test runs make_dist()
# in R and checks that the resulting distribution's mean, variance, and
# selected quantiles match the Julia reference within a generous tolerance.
# Cases for families this R package does not yet implement are filtered out
# at load time.
#
# If jsonlite is not installed, or the oracle file is missing, these tests
# skip rather than fail.

oracle_path <- function() {
  # testthat::test_path resolves to tests/testthat/ both interactively and
  # under R CMD check.
  testthat::test_path("data", "cross_oracle.json")
}

# Families this R package currently implements. The oracle JSON is the full
# Julia battery; we filter at load time to whatever R covers today. As more
# families are added to the R package, extend this vector — eventually it
# should reach Julia/Python parity.
SUPPORTED_FAMILIES <- c("gamma", "exponential", "logistic", "beta", "normal",
                        "lognormal")

closed_form_mean <- function(name, params) {
  switch(
    name,
    gamma       = params$shape / params$rate,
    exponential = 1 / params$rate,
    logistic    = params$location,
    beta        = params$shape1 / (params$shape1 + params$shape2),
    normal      = params$mean,
    lognormal   = exp(params$meanlog + params$sdlog^2 / 2),
    stop("no closed-form mean wired for ", name)
  )
}

closed_form_var <- function(name, params) {
  switch(
    name,
    gamma       = params$shape / params$rate^2,
    exponential = 1 / params$rate^2,
    logistic    = (pi^2 / 3) * params$scale^2,
    beta        = {
      a <- params$shape1; b <- params$shape2
      a * b / ((a + b)^2 * (a + b + 1))
    },
    normal      = params$sd^2,
    lognormal   = {
      s2 <- params$sdlog^2
      (exp(s2) - 1) * exp(2 * params$meanlog + s2)
    },
    stop("no closed-form var wired for ", name)
  )
}

coerce_kwargs <- function(kw) {
  # The oracle emits "quantiles" as a list of two-element lists; convert
  # those back to a list of length-2 numeric vectors (the R API form).
  out <- kw
  if (!is.null(kw$quantiles)) {
    out$quantiles <- lapply(kw$quantiles, function(pair) as.numeric(unlist(pair)))
  }
  out
}

parse_value <- function(x) {
  if (is.character(x)) {
    if (x == "inf") return(Inf)
    if (x == "-inf") return(-Inf)
    if (x == "nan") return(NaN)
  }
  as.numeric(x)
}

skip_if_no_oracle <- function() {
  testthat::skip_if_not_installed("jsonlite")
  path <- oracle_path()
  if (!file.exists(path)) {
    testthat::skip(sprintf("Oracle missing: %s", path))
  }
  path
}

load_oracle <- function() {
  path <- skip_if_no_oracle()
  jsonlite::fromJSON(path, simplifyVector = FALSE)
}


test_that("cross-oracle constructors agree with Julia", {
  oracle <- load_oracle()
  cases <- Filter(function(c) c$py_name %in% SUPPORTED_FAMILIES, oracle$constructors)
  testthat::expect_gt(length(cases), 0)

  for (case in cases) {
    name <- case$py_name
    kw <- coerce_kwargs(case$kwargs)
    expected <- case$expected
    label <- sprintf("%s(%s)", name,
                     paste(names(kw), "=", sapply(kw, function(v) {
                       if (is.list(v)) "quantiles" else format(v)
                     }), collapse = ", "))

    d <- do.call(make_dist, c(list(dist = name), kw))

    exp_mean <- parse_value(expected$mean)
    exp_var  <- parse_value(expected$var)

    if (is.finite(exp_mean)) {
      got <- closed_form_mean(name, d$params)
      testthat::expect_equal(got, exp_mean, tolerance = 1e-5,
                             info = sprintf("%s: mean", label))
    }
    if (is.finite(exp_var)) {
      got <- closed_form_var(name, d$params)
      testthat::expect_equal(got, exp_var, tolerance = 1e-5,
                             info = sprintf("%s: var", label))
    }

    # Quantile parity via $q (continuous only — discrete families would
    # disagree on tie-breaking conventions, but R only covers continuous
    # families anyway).
    if (isFALSE(expected$discrete) && !is.null(expected$ppf)) {
      for (p_str in names(expected$ppf)) {
        p <- as.numeric(p_str)
        q_jl <- parse_value(expected$ppf[[p_str]])
        if (!is.finite(q_jl)) next
        q_r <- d$q(p)
        testthat::expect_equal(q_r, q_jl, tolerance = 1e-5,
                               info = sprintf("%s: q(%s)", label, p_str))
      }
    }
  }
})


test_that("cross-oracle dist_exists agrees with Julia", {
  oracle <- load_oracle()
  # R does not yet support the `support=` (truncation) kwarg, so skip any
  # feasibility cases that depend on it.
  cases <- Filter(
    function(c) c$py_name %in% SUPPORTED_FAMILIES && is.null(c$support),
    oracle$feasibility
  )
  testthat::expect_gt(length(cases), 0)

  for (case in cases) {
    name <- case$py_name
    kw <- coerce_kwargs(case$kwargs)
    expected <- isTRUE(case$expected)
    label <- sprintf("%s(%s)", name,
                     paste(names(kw), "=", sapply(kw, format),
                           collapse = ", "))

    actual <- do.call(dist_exists, c(list(dist = name), kw))
    testthat::expect_identical(actual, expected, info = label)
  }
})
